#!/bin/bash

# Marcin Dąbrowski 315370
# Lista 2
# Zadanie 7

for file in "$@"
do
    size=$(($(du -ac "$file" 2>/dev/null | awk 'NR>1 { print $1 }')+size))
done
echo "Your files fit in these mounted filesystems:"
df | awk 'NR>1 { if($size<=$4) print $6; }'
